In [1]:
import pandas as pd
import numpy as np
from sklearn import neighbors as nei
from sklearn import metrics as met

USER TO USER COLLABORATIVE FILTERING APPROACH

In [ ]:
data = pd.read_csv("train.csv")
data.head()

   userID  movieID  rating
0    4490     2109       4
1    5839     3471       4
2    5382      150       3
3    1262     1237       5
4    6005     2273       4

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990209 entries, 0 to 990208
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   userID   990209 non-null  int64
 1   movieID  990209 non-null  int64
 2   rating   990209 non-null  int64
dtypes: int64(3)
memory usage: 22.7 MB

In [ ]:
U = data.pivot("userID", "movieID", "rating")
U.head()

movieID  1     2     3     4     5     6     ...  3947  3948  3949  3950  3951  3952
userID                                       ...
1         3.0   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
2         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
4         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
5         NaN   NaN   NaN   NaN   NaN   3.0  ...   NaN   NaN   NaN   NaN   NaN   NaN

[5 rows x 3705 columns]

In [ ]:
U.mean(axis=1)

userID
1       3.571429
2       3.878049
3       3.800000
4       3.711443
5       3.299312
          ...
6036    3.142132
6037    4.190476
6038    3.900000
6039    3.708661
6040    4.188679
Length: 6040, dtype: float64

In [ ]:
U_scaled = U - U.mean(axis=1).values.reshape(-1, 1)
U_scaled.fillna(0, inplace=True)
U_scaled.head()

movieID      1     2     3     4     5     ...  3948  3949  3950  3951  3952
userID                                     ...
1       -0.571429   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
2        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
3        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
4        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
5        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0

[5 rows x 3705 columns]

In [ ]:
U_scaled.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6040 entries, 1 to 6040
Columns: 3705 entries, 1 to 3952
dtypes: float64(3705)
memory usage: 170.8 MB

In [ ]:
train_size = 500
train = U_scaled[:train_size]
test = U_scaled[train_size:]

In [ ]:
train.head()

movieID      1     2     3     4     5     ...  3948  3949  3950  3951  3952
userID                                     ...
1       -0.571429   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
2        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
3        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
4        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
5        0.000000   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0

[5 rows x 3705 columns]

In [ ]:
test.head()

movieID  1         2     3         4     5     ...  3948  3949  3950  3951  3952
userID                                         ...
501       0.0  0.000000   0.0  0.000000   0.0  ...   0.0   0.0   0.0   0.0   0.0
502       0.0  0.000000   0.0 -0.752119   0.0  ...   0.0   0.0   0.0   0.0   0.0
503       0.0  0.000000   0.0  0.000000   0.0  ...   0.0   0.0   0.0   0.0   0.0
504       0.0  0.000000   0.0  0.000000   0.0  ...   0.0   0.0   0.0   0.0   0.0
505       0.0 -0.920128   0.0  0.000000   0.0  ...   0.0   0.0   0.0   0.0   0.0

[5 rows x 3705 columns]

1- First Structure

In [ ]:
nn = nei.NearestNeighbors(n_neighbors=train_size)
nn.fit(train)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=500, p=2,
                 radius=1.0)

In [ ]:
myPreds = []
realLabels = []
k = 100
for userId in test.index:
  print(userId)
  if userId == 515:
    break
  for movieId in test.columns:
    #userId = 501
    #movieId = 2
    if not np.isnan(U.loc[userId, movieId]): 
      test_user = test.loc[userId:userId, :]
      indices = nn.kneighbors(test_user, return_distance=False)[0] + 1

      ratings = []
      i = 0
      while len(ratings) < k and i < len(indices):
        if not np.isnan(U.loc[indices[i], movieId]):
          ratings.append(U.loc[indices[i], movieId])
        i += 1

      if len(ratings) > 0:
        pred = sum(ratings)/len(ratings)
        myPreds.append(pred)

        real_label = U.loc[userId, movieId]
        realLabels.append(real_label)

501
502
503
504
505
506
507
508
509
510
511
512
513
514
515

In [ ]:
met.mean_squared_error(realLabels, myPreds, squared=False)

0.9444314299451578

In [ ]:
nn = nei.NearestNeighbors(n_neighbors=train_size,leaf_size=30, metric='cosine')
nn.fit(train)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=500, p=2,
                 radius=1.0)

In [ ]:
myPreds = []
realLabels = []
k = 100
for userId in test.index:
  print(userId)
  if userId == 515:
    break
  for movieId in test.columns:
    #userId = 501
    #movieId = 2
    if not np.isnan(U.loc[userId, movieId]): 
      test_user = test.loc[userId:userId, :]
      indices = nn.kneighbors(test_user, return_distance=False)[0] + 1

      ratings = []
      i = 0
      while len(ratings) < k and i < len(indices):
        if not np.isnan(U.loc[indices[i], movieId]):
          ratings.append(U.loc[indices[i], movieId])
        i += 1

      if len(ratings) > 0:
        pred = sum(ratings)/len(ratings)
        myPreds.append(pred)

        real_label = U.loc[userId, movieId]
        realLabels.append(real_label)

501
502
503
504
505
506
507
508
509
510
511
512
513
514
515

In [ ]:
met.mean_squared_error(realLabels, myPreds, squared=False)

0.9324202220956099

2- Second Structure

In [ ]:
U.head()

movieID  1     2     3     4     5     6     ...  3947  3948  3949  3950  3951  3952
userID                                       ...
1         3.0   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
2         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
4         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
5         NaN   NaN   NaN   NaN   NaN   3.0  ...   NaN   NaN   NaN   NaN   NaN   NaN

[5 rows x 3705 columns]

In [ ]:
train = U[:train_size]
test = U[train_size:]

In [ ]:
train.head()

movieID  1     2     3     4     5     6     ...  3947  3948  3949  3950  3951  3952
userID                                       ...
1         3.0   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
2         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
3         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
4         NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
5         NaN   NaN   NaN   NaN   NaN   3.0  ...   NaN   NaN   NaN   NaN   NaN   NaN

[5 rows x 3705 columns]

In [ ]:
test.head()

movieID  1     2     3     4     5     6     ...  3947  3948  3949  3950  3951  3952
userID                                       ...
501       NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
502       NaN   NaN   NaN   3.0   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
503       NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
504       NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
505       NaN   2.0   NaN   NaN   NaN   5.0  ...   NaN   NaN   NaN   NaN   NaN   NaN

[5 rows x 3705 columns]

In [ ]:
k = 100
myPreds = []
realLabels = []
for userId in test.index:
  print(userId)
  if userId == 515:
    break
  for movieId in test.columns:
    if not np.isnan(test.loc[userId, movieId]):
      #userId = 501
      #movieId = 2

      filtered_train = train.dropna(subset=[movieId])
      filtered_train = filtered_train - filtered_train.mean(axis=1).values.reshape(-1,1)
      filtered_train.fillna(0, inplace=True)
      if k < len(filtered_train):
        nn = nei.NearestNeighbors(n_neighbors=k)
        nn.fit(filtered_train)

        test_row = test.loc[userId:userId, :]
        test_row = test_row - test_row.mean(axis=1).values.reshape(-1,1)
        test_row.fillna(0, inplace=True)

        indices = nn.kneighbors(test_row, return_distance=False)[0]

        userIds = filtered_train.iloc[indices, :].index
        pred = train.loc[userIds, movieId].values.mean()
        myPreds.append(pred)

        real_label = test.loc[userId, movieId]
        realLabels.append(real_label)

501
502
503
504
505
506
507
508
509
510
511
512
513
514
515

In [ ]:
met.mean_squared_error(realLabels, myPreds, squared=False)

0.868442662092701

In [ ]:
k = 100
myPreds = []
realLabels = []
for userId in test.index:
  print(userId)
  if userId == 515:
    break
  for movieId in test.columns:
    if not np.isnan(test.loc[userId, movieId]):
      #userId = 501
      #movieId = 2

      filtered_train = train.dropna(subset=[movieId])
      filtered_train = filtered_train - filtered_train.mean(axis=1).values.reshape(-1,1)
      filtered_train.fillna(0, inplace=True)
      if k < len(filtered_train):
        nn = nei.NearestNeighbors(n_neighbors=k,metric='correlation')
        nn.fit(filtered_train)

        test_row = test.loc[userId:userId, :]
        test_row = test_row - test_row.mean(axis=1).values.reshape(-1,1)
        test_row.fillna(0, inplace=True)

        indices = nn.kneighbors(test_row, return_distance=False)[0]

        userIds = filtered_train.iloc[indices, :].index
        pred = train.loc[userIds, movieId].values.mean()
        myPreds.append(pred)

        real_label = test.loc[userId, movieId]
        realLabels.append(real_label)

501
502
503
504
505
506
507
508
509
510
511
512
513
514
515

In [ ]:
met.mean_squared_error(realLabels, myPreds, squared=False)

0.8050674297433517

Prediction with User to User Collaborative Filtering

In [ ]:
test = pd.read_csv("test_without_labels.csv")
test.head()

         IDs
0   629_2683
1    601_904
2  5673_3717
3  5616_1721
4  1099_3697

In [ ]:
x = pd.DataFrame(test.IDs.str.split('_',1).tolist(),
                         columns = ['userId','movieId'])
print(x)

     userId movieId
0       629    2683
1       601     904
2      5673    3717
3      5616    1721
4      1099    3697
...     ...     ...
9994   4198    3671
9995    566    3148
9996   5531    2105
9997   4650     377
9998   4919    2094

[9999 rows x 2 columns]

In [ ]:
df_test = pd.DataFrame(x)
df_test

     userId movieId
0       629    2683
1       601     904
2      5673    3717
3      5616    1721
4      1099    3697
...     ...     ...
9994   4198    3671
9995    566    3148
9996   5531    2105
9997   4650     377
9998   4919    2094

[9999 rows x 2 columns]

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   userId   9999 non-null   object
 1   movieId  9999 non-null   object
dtypes: object(2)
memory usage: 156.4+ KB

In [ ]:
df_test['userId'] = df_test['userId'].astype(str).astype(int)
df_test['movieId'] = df_test['movieId'].astype(str).astype(int)

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   userId   9999 non-null   int64
 1   movieId  9999 non-null   int64
dtypes: int64(2)
memory usage: 156.4 KB

In [ ]:
myPreds = []
k = 50

for i in range(len(df_test)):
  userId= df_test.userId[i]
  movieId=df_test.movieId[i]
  filtered_train = U.dropna(subset=[movieId])
  filtered_train = filtered_train - filtered_train.mean(axis=1).values.reshape(-1,1)
  filtered_train.fillna(0, inplace=True)
  if k < len(filtered_train):
    nn = nei.NearestNeighbors(n_neighbors=k,metric="correlation",)
    nn.fit(filtered_train)

    test_row = U.loc[userId:userId, :]
    test_row = test_row - test_row.mean(axis=1).values.reshape(-1,1)
    test_row.fillna(0, inplace=True)

    indices = nn.kneighbors(test_row, return_distance=False)[0]

    userIds = filtered_train.iloc[indices, :].index
    pred = U.loc[userIds, movieId].values.mean()
    myPreds.append(pred)
  else:
    test_row2 =U.loc[userId:userId, :]
    pred2=test_row2.mean(axis=1).values.reshape(-1,1)[0][0]
    myPreds.append(pred2)

In [ ]:
len(myPreds)

9999

In [ ]:
test2 = test.copy()
test2["rating"]= myPreds

In [ ]:
test2.head()

         IDs  rating
0   629_2683    3.02
1    601_904    4.34
2  5673_3717    2.70
3  5616_1721    3.36
4  1099_3697    2.84

In [ ]:
from google.colab import files
test2.to_csv('submission1.csv',index=False) 
files.download('submission1.csv')